In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3.5])
arr

array([1. , 2. , 3.5])

In [7]:
arr.dtype

dtype('float64')

In [8]:
np.arange(0, 100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
matrix_3d = np.arange(0, 100).reshape(5, 5, -1)

In [20]:
matrix_3d[:,0,:]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [21]:
first_frame, second_frame = matrix_3d[0,:,:],matrix_3d[1,:,:]

In [22]:
first_frame


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
first_frame[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [25]:
first_frame.swapaxes(0,1)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [26]:
arr1 = np.arange(10, 30, 2)

In [27]:
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
arr2 = np.full((10,), 5)

In [29]:
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [30]:
stacked = np.vstack((arr1, arr2))

In [31]:
stacked

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

In [33]:
stacked = np.hstack((stacked, np.array([1, 2])))

ValueError: all the input arrays must have same number of dimensions

In [34]:
to_stack = np.array([1000, 2000])[:, np.newaxis]

In [35]:
to_stack

array([[1000],
       [2000]])

In [36]:
stacked = np.hstack((stacked, to_stack))

In [37]:
stacked

array([[  10,   12,   14,   16,   18,   20,   22,   24,   26,   28, 1000],
       [   5,    5,    5,    5,    5,    5,    5,    5,    5,    5, 2000]])

In [38]:
stacked[stacked == 5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [39]:
stacked == 5

array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False]])

In [40]:
stacked[stacked == 5] = 100

In [41]:
stacked

array([[  10,   12,   14,   16,   18,   20,   22,   24,   26,   28, 1000],
       [ 100,  100,  100,  100,  100,  100,  100,  100,  100,  100, 2000]])

In [42]:
mean_value = first_frame.mean()

In [43]:
mean_value

9.5

In [46]:
first_frame.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [45]:
first_frame

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
first_frame.sum()

190

In [48]:
np.add(first_frame, second_frame)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [49]:
np.subtract(first_frame, second_frame)

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [50]:
np.multiply(first_frame, second_frame)

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [51]:
np.matmul(first_frame, second_frame.T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [52]:
mat = np.full((3, 5), 2)
mat

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [54]:
2 * mat

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [60]:
np.arange(3)[:, np.newaxis] * mat

array([[0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4]])

In [59]:
np.arange(3).shape

(3,)