# Live Demo 04 - Numpy and Scipy

Numpy import statement

In [50]:
import numpy as np

In [51]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
arr = np.arange(0, 100, 2)

In [53]:
arr = np.arange(0, 100, 0.25)

In [54]:
arr = np.arange(0, 100)
len(arr)

100

In [55]:
arr.shape

(100,)

In [56]:
np.reshape?

In [57]:
matrix = arr.reshape(10, 10)
matrix.shape

(10, 10)

In [58]:
len(matrix)

10

In [59]:
matrix = arr.reshape(20, -1)
matrix.shape

(20, 5)

In [60]:
matrix_3d = arr.reshape(5, 5, -1)
print('matrix_3d: ndim = {}, shape = {}, size = {}, dtype = {}'.format(
    matrix_3d.ndim, matrix_3d.shape, matrix_3d.size, matrix_3d.dtype
))

matrix_3d: ndim = 3, shape = (5, 5, 4), size = 100, dtype = int64


In [61]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [62]:
matrix_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [63]:
matrix_3d[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [64]:
matrix_3d[:,0,:]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [65]:
matrix_3d[:,:,0]

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [66]:
first_frame, second_frame = matrix_3d[:,:,0], matrix_3d[:,:,1]
first_frame

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [67]:
first_frame.shape

(5, 5)

In [68]:
# slicing
first_frame[1:3, 1:4]

array([[24, 28, 32],
       [44, 48, 52]])

In [69]:
transposed_frame = first_frame.T
transposed_frame

array([[ 0, 20, 40, 60, 80],
       [ 4, 24, 44, 64, 84],
       [ 8, 28, 48, 68, 88],
       [12, 32, 52, 72, 92],
       [16, 36, 56, 76, 96]])

In [70]:
transposed_frame = first_frame.swapaxes(0,1)
transposed_frame

array([[ 0, 20, 40, 60, 80],
       [ 4, 24, 44, 64, 84],
       [ 8, 28, 48, 68, 88],
       [12, 32, 52, 72, 92],
       [16, 36, 56, 76, 96]])

## Stacking, concatenating, filtering

In [71]:
arr1 = np.arange(10, 30, 2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [72]:
arr2 = np.full((10 ,), 5)
arr2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [73]:
stacked = np.vstack((arr1, arr2))
stacked

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5]])

In [74]:
stacked = np.hstack((stacked, np.array([1, 2])))

ValueError: all the input arrays must have same number of dimensions

In [75]:
tostack = np.array([1000, 2000])[:, np.newaxis]
print(tostack)
stacked = np.hstack((stacked, tostack))
stacked

[[1000]
 [2000]]


array([[  10,   12,   14,   16,   18,   20,   22,   24,   26,   28, 1000],
       [   5,    5,    5,    5,    5,    5,    5,    5,    5,    5, 2000]])

In [76]:
concatenated = np.concatenate((arr1, arr2))
concatenated

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5])

In [77]:
stacked[stacked == 5] = 100
stacked

array([[  10,   12,   14,   16,   18,   20,   22,   24,   26,   28, 1000],
       [ 100,  100,  100,  100,  100,  100,  100,  100,  100,  100, 2000]])

In [78]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 
                  'Joe', 'Bob', 'Will', 'Joe', 'Will'])
names == 'Bob'

array([ True, False, False,  True, False, False, False,  True, False,
       False, False])

In [79]:
data = np.random.randn(11, 4)
data

array([[-0.80151563, -0.88253813,  0.63903948,  0.13966193],
       [-0.8947935 , -1.110423  , -0.87162988, -0.93563766],
       [ 0.20626146,  0.86236255,  1.63100472, -0.01100938],
       [-1.38263915,  1.923483  , -1.35834818,  0.33675543],
       [ 0.42016658,  0.48666998, -0.14438875, -0.46178685],
       [-0.52810139, -0.62435485,  0.80567029, -0.66183994],
       [-0.49378906, -0.03010415, -0.69083429, -0.75424175],
       [ 0.17336684,  0.65479648, -1.58184513, -0.58921207],
       [-0.98714987, -0.27562451,  1.48291567,  1.59896626],
       [-0.93245006, -0.2578689 , -0.92280339,  0.48055852],
       [-0.90661382, -2.25985279, -0.00389786, -0.09674889]])

In [80]:
data [names == 'Bob']

array([[-0.80151563, -0.88253813,  0.63903948,  0.13966193],
       [-1.38263915,  1.923483  , -1.35834818,  0.33675543],
       [ 0.17336684,  0.65479648, -1.58184513, -0.58921207]])

## Vectorized methods/functions

In [81]:
mean_value = first_frame.mean()
mean_value

48.0

In [82]:
mean_values_by_column = first_frame.mean(axis=1)
mean_values_by_column

array([ 8., 28., 48., 68., 88.])

In [83]:
mean_values_by_row = first_frame.mean(axis=0)
mean_values_by_row

array([40., 44., 48., 52., 56.])

In [84]:
frame_sum = 0
for el in np.nditer(first_frame):
    frame_sum += el
frame_sum

1200

In [85]:
frame_sum = first_frame.sum()
frame_sum

1200

In [86]:
frame_sum = first_frame.sum(axis=0)
frame_sum

array([200, 220, 240, 260, 280])

## Element-wise operations on arrays

In [87]:
np.add(first_frame, second_frame)

array([[  1,   9,  17,  25,  33],
       [ 41,  49,  57,  65,  73],
       [ 81,  89,  97, 105, 113],
       [121, 129, 137, 145, 153],
       [161, 169, 177, 185, 193]])

The one above is what is called a simmetrical square matrix

In [88]:
np.subtract(second_frame, first_frame)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [89]:
np.multiply(second_frame, first_frame)

array([[   0,   20,   72,  156,  272],
       [ 420,  600,  812, 1056, 1332],
       [1640, 1980, 2352, 2756, 3192],
       [3660, 4160, 4692, 5256, 5852],
       [6480, 7140, 7832, 8556, 9312]])

In [90]:
np.matmul(second_frame, first_frame)

array([[ 2600,  2780,  2960,  3140,  3320],
       [ 6600,  7180,  7760,  8340,  8920],
       [10600, 11580, 12560, 13540, 14520],
       [14600, 15980, 17360, 18740, 20120],
       [18600, 20380, 22160, 23940, 25720]])

In [91]:
np.exp(first_frame)

array([[1.00000000e+00, 5.45981500e+01, 2.98095799e+03, 1.62754791e+05,
        8.88611052e+06],
       [4.85165195e+08, 2.64891221e+10, 1.44625706e+12, 7.89629602e+13,
        4.31123155e+15],
       [2.35385267e+17, 1.28516001e+19, 7.01673591e+20, 3.83100800e+22,
        2.09165950e+24],
       [1.14200739e+26, 6.23514908e+27, 3.40427605e+29, 1.85867175e+31,
        1.01480039e+33],
       [5.54062238e+34, 3.02507732e+36, 1.65163625e+38, 9.01762841e+39,
        4.92345829e+41]])

In [92]:
from scipy.linalg import expm
expm(first_frame)


array([[3.67316016e+109, 4.01382494e+109, 4.35448973e+109,
        4.69515452e+109, 5.03581931e+109],
       [1.02740310e+110, 1.12268891e+110, 1.21797473e+110,
        1.31326054e+110, 1.40854636e+110],
       [1.68749018e+110, 1.84399533e+110, 2.00050048e+110,
        2.15700563e+110, 2.31351078e+110],
       [2.34757726e+110, 2.56530175e+110, 2.78302623e+110,
        3.00075072e+110, 3.21847521e+110],
       [3.00766434e+110, 3.28660816e+110, 3.56555199e+110,
        3.84449581e+110, 4.12343963e+110]])

## Broadcasting

In [98]:
matrix = np.full((3,5), 1)


In [99]:
matrix

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [100]:
2 * matrix

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [101]:
np.arange(5) * matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [102]:
np.arange(3) * matrix

ValueError: operands could not be broadcast together with shapes (3,) (3,5) 

In [103]:
column_vec = np.arange(3)[:, np.newaxis]
column_vec

array([[0],
       [1],
       [2]])

In [104]:
column_vec * matrix

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])